#!/bin/bash
sudo apt install python3-wstool vim git libtool cmake cython atop htop openssh-server curl

### ROS noetic
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
sudo apt update
sudo apt install ros-noetic-sbpl libsuitesparse-dev ros-noetic-libg2o ros-noetic-costmap-2d ros-noetic-nav-core ros-noetic-costmap-converter ros-noetic-move-base-msgs ros-noetic-laser-proc ros-noetic-urg-c ros-noetic-joy ros-noetic-amcl ros-noetic-map-server ros-noetic-sick-tim

### permission for laser scanner
sudo usermod -a -G dialout $USER

### environment settings
mkdir -p root/.{$USER}
echo "export ROS_IP=" >> root/.{$USER}/env.sh


# install ropod software
cd /root/
WORKSPACE_NAME="catkin_workspace"
mkdir -p ropod-project-software/${WORKSPACE_NAME}/src
cd ropod-project-software/${WORKSPACE_NAME}/src
git clone https://github.com/tue-ropod/tree-ropod.git ./
git checkout feature/remove_ed_dependency


cd ..
wstool init
cd src
wstool up
echo "source /root/ropod-project-software/${WORKSPACE_NAME}/src/platform/setup/devpc/setup.bash"  >> root/.bashrc
echo "source /root/ropod-project-software/catkin_workspace/src/platform/ropod_tue_2_bringup/setup.bash"  >> root/.bashrc


source root/ropod-project-software/${WORKSPACE_NAME}/src/platform/setup/devpc/setup.bash
rosdep update;rosdep install --from-path . -i -y;
# cd ~/ropod-project-software/${WORKSPACE_NAME}; catkin_make;

